import createClient, { type Middleware } from "openapi-fetch";

import type { paths } from "@/openapi.gen"; // generated by openapi-typescript

import { zitadel } from "./zitadel";

export const api = createClient<paths>({ baseUrl: "http://localhost:3000" });

api.use({
  async onRequest({ request }) {
    const user = await zitadel.userManager.getUser();
    if (user?.id_token) {
      request.headers.set("Authorization", `Bearer ${user.id_token}`);
    }
    return request;
  },
} satisfies Middleware);
