import createClient from "openapi-fetch";

import { ApiError } from "@/libraries/errors";
import type { components, paths } from "@/openapi.gen"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:3000" });

export const api = {
  accounts: {
    create: async (body: components["schemas"]["CreateAccountPayload"]) => {
      const response = await client.POST("/api/accounts", { body });
      if (response.error !== undefined) {
        throw new ApiError(response.error);
      }
      return response.data;
    },

    list: async () => {
      const response = await client.GET("/api/accounts");
      if (response.error !== undefined) {
        throw new ApiError(response.error);
      }
      return response.data;
    },
  },

  principals: {
    me: async () => {
      const response = await client.GET("/api/principals/me");
      if (response.error !== undefined) {
        throw new ApiError(response.error);
      }
      return response.data;
    },
  },

  users: {
    create: async (body: components["schemas"]["PostUserPayload"]) => {
      await client.POST("/api/users", { body });
    },

    /**
     * Retrieve the user registerd for the current authenticated session, or
     * undefined if no user has been created.
     */
    me: async () => {
      const response = await client.GET("/api/users/me");
      if (response.error !== undefined) {
        if (response.error.status === 404) {
          return undefined;
        }
        throw new ApiError(response.error);
      }
      return response.data;
    },
  },
};
