import createClient from "openapi-fetch";

import type { components, paths } from "@/openapi.gen"; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: "http://localhost:3000" });

class ApiException {
  readonly type: string;
  readonly title?: string;
  readonly status: number;
  readonly detail: string;
  readonly instance: string;

  constructor(error: ApiErrorResponse) {
    this.type = error.type ?? "API_EXCEPTION";
    this.title = error.title ?? "Unknown API Exception";
    this.status = typeof error.status === "string" ? parseInt(error.status, 10) : (error.status ?? 500);
    this.detail = error.detail ?? "";
    this.instance = error.instance ?? "";
  }
}

// client.use({
//   async onRequest({ request }) {
//     if (bearer !== undefined) {
//       request.headers.set("Authorization", `Bearer ${bearer}`);
//     }
//     return request;
//   },
//   async onResponse({ response }) {
//     return response;
//   },
// } satisfies Middleware);

export const api = {
  accounts: {
    create: async (body: components["schemas"]["CreateAccountPayload"]) => {
      await client.POST("/api/accounts", { body });
    },

    list: async () => {
      const response = await client.GET("/api/accounts");
      if (response.error !== undefined) {
        throw new ApiException(response.error);
      }
      return response.data;
    },
  },

  principals: {
    me: async () => {
      const response = await client.GET("/api/principals/me");
      if (response.error !== undefined) {
        throw new ApiException(response.error);
      }
      return response.data;
    },
  },

  users: {
    create: async (body: components["schemas"]["PostUserPayload"]) => {
      await client.POST("/api/users", { body });
    },

    /**
     * Retrieve the user registerd for the current authenticated session, or
     * undefined if no user has been created.
     */
    me: async () => {
      const response = await client.GET("/api/users/me");
      if (response.error !== undefined) {
        if (response.error.status === 404) {
          return undefined;
        }
        throw new ApiException(response.error);
      }
      return response.data;
    },
  },
};

type ApiErrorResponse = {
  type?: string | null | undefined;
  title?: string | null | undefined;
  status?: string | number | null | undefined;
  detail?: string | null | undefined;
  instance?: string | null | undefined;
};
