// <auto-generated />
using System;
using Banking.Atomic.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking.Atomic.Database.Migrations
{
    [DbContext(typeof(AtomicDbContext))]
    partial class AtomicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Banking.Atomic.Repositories.Resources.AtomicRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("AtomicRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
