/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as UserRouteImport } from './routes/_user'
import { Route as UserIndexRouteImport } from './routes/_user.index'
import { Route as UserTransactionsRouteImport } from './routes/_user.transactions'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const UserTransactionsRoute = UserTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => UserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/register': typeof RegisterRoute
  '/transactions': typeof UserTransactionsRoute
}
export interface FileRoutesByTo {
  '/register': typeof RegisterRoute
  '/transactions': typeof UserTransactionsRoute
  '/': typeof UserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_user': typeof UserRouteWithChildren
  '/register': typeof RegisterRoute
  '/_user/transactions': typeof UserTransactionsRoute
  '/_user/': typeof UserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/register' | '/transactions' | '/'
  id: '__root__' | '/_user' | '/register' | '/_user/transactions' | '/_user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRoute: typeof UserRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/transactions': {
      id: '/_user/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof UserTransactionsRouteImport
      parentRoute: typeof UserRoute
    }
  }
}

interface UserRouteChildren {
  UserTransactionsRoute: typeof UserTransactionsRoute
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserTransactionsRoute: UserTransactionsRoute,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  UserRoute: UserRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
