// <auto-generated />
using System;
using Banking.Principal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking.Principals.Persistence.Migrations
{
    [DbContext(typeof(PrincipalDbContext))]
    [Migration("20260306021856_Principals-init")]
    partial class Principalsinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Banking.Principal.Principal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("Banking.Principal.PrincipalAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId", "Domain");

                    b.HasIndex("PrincipalId", "Domain", "Key")
                        .IsUnique();

                    b.ToTable("PrincipalAttributes");
                });

            modelBuilder.Entity("Banking.Principal.PrincipalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("PrincipalIdentities");
                });

            modelBuilder.Entity("Banking.Principal.PrincipalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId", "Role")
                        .IsUnique();

                    b.ToTable("PrincipalRoles");
                });

            modelBuilder.Entity("Banking.Principal.PrincipalAttribute", b =>
                {
                    b.HasOne("Banking.Principal.Principal", null)
                        .WithMany("Attributes")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banking.Principal.PrincipalIdentity", b =>
                {
                    b.HasOne("Banking.Principal.Principal", null)
                        .WithMany("Identities")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banking.Principal.PrincipalRole", b =>
                {
                    b.HasOne("Banking.Principal.Principal", null)
                        .WithMany("Roles")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banking.Principal.Principal", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Identities");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
