// <auto-generated />
using System;
using Banking.AtomicFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Banking.AtomicFlow.Persistence.Migrations
{
    [DbContext(typeof(AtomicFlowDbContext))]
    [Migration("20260307140905_Atomic-flow-init")]
    partial class Atomicflowinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Banking.AtomicFlow.Repositories.Resources.AtomicFlowRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RollbackType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.ToTable("AtomicFlowRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
